AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - bin/**
    - spec/dummy/config/initializers/secret_token.rb
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 160
Metrics/AbcSize:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - helena.gemspec
  ExcludedMethods:
    - describe
    - context
    - scenario
    - it
    - feature
