language: ruby
rvm:
  - 2.2.2
  - 2.3.0
  - 2.3.1

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

services:
  - mongodb

cache: bundler
sudo: false

matrix:
  include:
  - rvm: 2.1
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.2.0
    gemfile: gemfiles/rails_4.2.gemfile
