common: &common
  adapter: postgresql
  username: postgres
  host: localhost

development:
  <<: *common
  database: helena_dev

test:
  <<: *common
  database: helena_test

production:
  <<: *common
  database: helena

