development:
  sessions:
    default:
      database: helena_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: helena_test
      hosts:
        - localhost:27017

